### ISSUE TITLE
Would you consider adding an alias for magic?

### ISSUE THREAD

**Issue by dlo** [ArtSabintsev/Magic#6]
The name "magic" in itself doesn't give much of an indication for what the function does. To anyone reading my codebase, it looks like I've sprinkled a bit of magic everywhere (perhaps I have...).

Would you consider adding an alias (e.g., "printD") to indicate that this is a amp'ed up version of print?

**Comment by ArtSabintsev** [comment]
Sure :) 

How about calling it DLog?

**Comment by ArtSabintsev** [comment]
Actually, how about a type alias named MagicLog(_:)?

**Comment by dlo** [comment]
Even better. :+1:

**Comment by ArtSabintsev** [comment]
Totally forgot about this. 

How about you make the alias on your end and use it within your projects?

(I don't know how widely used this project is, but I like keeping it nice and tiny).

**Comment by ArtSabintsev** [comment]
Closing this Issue.
